### ISSUE TITLE
pitch accuracy

### ISSUE THREAD

**Issue by zhezhao1989** [liuruijin17/LSTR#1]
I have a question. How is the pitch accuracy by the transform model inference?

**Comment by pineapplegreen** [comment]
Sorry for getting back to you so late.

Are you talking about the difference in accuracy between considering pitch angle and not considering pitch angle in the lane shape model? @zhezhao1989

**Comment by liuruijin17** [comment]
Sorry for getting back to you so late!

Are you talking about the difference in accuracy between considering pitch angle and not considering pitch angle in the lane shape model? @zhezhao1989

**Comment by zhezhao1989** [comment]
> Sorry for getting back to you so late!
> 
> Are you talking about the difference in accuracy between considering pitch angle and not considering pitch angle in the lane shape model? @zhezhao1989

I guess the transform model can get the camera pitch, right? So, I am curious about the camera pitch accuracy.

**Comment by liuruijin17** [comment]
> > Sorry for getting back to you so late!
> > Are you talking about the difference in accuracy between considering pitch angle and not considering pitch angle in the lane shape model? @zhezhao1989
> 
> I guess the transform model can get the camera pitch, right? So, I am curious about the camera pitch accuracy. @liuruijin17
> For example, if we use the model for a video sequence, can we get a smoothed camera pitch value for each image of the video sequence?

No, our model doesn't explicitly predict the pitch angle. There are no data about camera parameters and road curvature; by far, it predicts parameters that are a combination of physical variables such as pitch angle and focal length.

Our lane shape model is a **2D** representation whose parameters are combinations of physical variables. If you were to get those physical variables' values, the camera parameters need to be obtained first, which is not a concern in this paper.

If you use the model for a video sequence, you can get values that are combinations of the pitch value and other physical parameters. For example, you can get a sequence f<sup>''</sup><sub>t</sub> , where t indexes the video frames and f<sup>''</sup><sub>t</sub>=f<sub>t</sub>sinφ<sub>t</sub>.  If your model is trained on a suitable dataset, the estimated f<sup>''</sup> on test set can be a consistency approximation which means you directly obtain an effective physical descriptor on test set without any additional calibration or sensors.

**Comment by zhezhao1989** [comment]
> > > Sorry for getting back to you so late!
> > > Are you talking about the difference in accuracy between considering pitch angle and not considering pitch angle in the lane shape model? @zhezhao1989
> > 
> > 
> > I guess the transform model can get the camera pitch, right? So, I am curious about the camera pitch accuracy. @liuruijin17
> > For example, if we use the model for a video sequence, can we get a smoothed camera pitch value for each image of the video sequence?
> 
> No, our model doesn't explicitly predict the pitch angle. There are no data about camera parameters and road curvature; by far, it predicts parameters that are a combination of physical variables such as pitch angle and focal length.
> 
> Our lane shape model is a **2D** representation whose parameters are combinations of physical variables. If you were to get those physical variables' values, the camera parameters need to be obtained first, which is not a concern in this paper.
> 
> If you use the model for a video sequence, you can get values that are combinations of the pitch value and other physical parameters. For example, you can get a sequence f''t , where t indexes the video frames and f''t=ftsinφt. If your model is trained on a suitable dataset, the estimated f'' on test set can be a consistency approximation which means you directly obtain an effective physical descriptor on test set without any additional calibration or sensors.

thanks for your reply. from f''t=ftsinφt, if we know the camera focal length f in pixels from camera calibration, we can get the camera pitch, right( sinφ = f"/f )? but I guess this computed φ is not the truth camera pitch value, which I mean φ maybe not equal to the truth camera pitch value.

**Comment by liuruijin17** [comment]
It is difficult to give conclusions about the accuracy of the values without actual data.

The network outputs a descriptor f<sup>''</sup> that varies with focal length and pitch angle. Assuming f is constant, you can think that when f<sup>''</sup> is constant, then the pitch angle is unchanged, which means you don't need to know the specific value of the pitch angle.

However, the network doesn't get any information about the camera parameters (for example, the f should be a constant for subsequent images). The only thing the network gets is the 2D labeled points which means the network thinks every image was taken by a specific virtual camera, so it learns to find some suitable descriptors to fit lanes well and that's it. No extra information and no need to verify the real 3D values.

If you really really want to verify the true value, as I said, 
first, you get the focal length in pixels (assume 100). 
Then you maintain this camera and collect a dataset whose labeled 3D points are truly located on the lanes, then you project those 3D points into a 2D image plane to form the dataset. 
Next, you need to formulate the lane shape model when f=100, and set the sinφ to be an output parameter, and use it to represent all the variables related to angle.
In this case, the output set for a certain lane is (k', sinφ, m', n', b', α, β) (see Eq.(3) in my paper) and the output sinφ must >-1 and <1.
Finally, you can verify what you want.

**Comment by zhezhao1989** [comment]
thanks a lot.
