### ISSUE TITLE
How does the model perform on embedded platforms?

### ISSUE THREAD

**Issue by wangjie0323** [liuruijin17/LSTR#11]
Thank you very much, I would like to know how this algorithm performs on embedded platforms such as rk3399, specifically the OPENAILAB EAI 610, and I look forward to your reply.

**Comment by liuruijin17** [comment]
Hi,
Thanks for your attention! I am not familiar with those platforms, and our resources cannot support us to test on them.
If you are interested in relevant experiments, please feel free to pull requests to supplement the relevant performance evaluation results.
