### ISSUE TITLE
How to genereate label_data_0313.json?

### ISSUE THREAD

**Issue by jinfagang** [liuruijin17/LSTR#15]
I downloaded Tusimple testset, the dataset looks like:

```
.
├── clips
│   ├── 0530
│   ├── 0531
│   └── 0601
├── readme.md
└── test_tasks_0627.json

```

where to found these:

```
label_data_0313.json
        label_data_0531.json
        label_data_0601.json
```

**Comment by liuruijin17** [comment]
Hi, 
0313, 0531, and 0601 are in the [train_set.zip](https://github.com/TuSimple/tusimple-benchmark/issues/3)

**Comment by Mohamad-Asif-Pir** [comment]
Hello i need ur help i have my own private dataset but without labelling,can u please tell me how to create .json file for labelling.

**Comment by MasterHM-ml** [comment]
> Hello i need ur help i have my own private dataset but without labelling,can u please tell me how to create .json file for labelling.

Hey Muhammad Asif! Did you found the tool to label custom data and get json file?
