### ISSUE TITLE
Parallel assumption and complex topologies

### ISSUE THREAD

**Issue by lz707** [liuruijin17/LSTR#2]
Hi Ruijin,

First of all, congratulations on the great work! The results look amazing, and I particularly liked the equation derivation part. 

If my understanding is correct, the paper used shape consistency constraint which basically assumes that the lanes are parallel polynomials. This perhaps covers only 90% of the case but it does not seem to address more complex topologies such as merges and splits. Any insights you could shed on this?

**Comment by liuruijin17** [comment]
Hi @lz707 ,
Thanks for your interest and sorry for getting back to you so late!

Yes, your understanding is correct. 
The current scenario considered in our method is one in which the vehicle is driving steadily on the road and the road is clearly marked with lane markings.

Merges and splits are a great follow-up. In this scenario the lane patterns get complicated and the global parallel assumptions obviously cause problems.
For example, there are 4 lanes near the freeway ramp, and the left 2 lanes are straight while the 2 on the right are curved. We think
1. a more flexible local parallel assumption that can automatically cluster lanes of the same shape.
2. a more diverse dataset containing the aforementioned lane patterns is also critical.

Some brief insights and I welcome in-depth discussion!
