### ISSUE TITLE
Optimize model parameters according to DETR.

### ISSUE THREAD

**Issue by lunachy** [liuruijin17/LSTR#20]
Do you make grid search about parameters of enc_layers、dec_layers?
According to DETR, more encoder layers and decoder layers are beneficial. Maybe enc_layers and dec_layers set to 3 at least.
![image](https://user-images.githubusercontent.com/10249962/101609482-fa351480-3a41-11eb-972a-bb45a56197fe.png)
![image](https://user-images.githubusercontent.com/10249962/101609529-04efa980-3a42-11eb-9f3e-6cd21216515d.png)

**Comment by liuruijin17** [comment]
Yes, we also tried it, but the performance was not that significantly improved (or even decreased), probably due to overfitting. We actually set up 2 directly and found the overall effect to be good :joy:, so we didn't carefully tune the number of transformer layers.

**Comment by lunachy** [comment]
According to the paper, I guess you test this on tusimple dataset.

**Comment by liuruijin17** [comment]
Yes, the TuSimple validation dataset.
