### ISSUE TITLE
Question about FPS?

### ISSUE THREAD

**Issue by harrylin-hyl** [liuruijin17/LSTR#24]
I noticed the FPS in your paper is 420, but I test the model of batch-size 1, and the FPS is 120 on 2080TI.
Whether the result is tested on batchsize=16? Why repeat the images to increase the number of batch-size will run faster?

**Comment by zxt881108** [comment]
#19

**Comment by voldemortX** [comment]
@liuruijin17 @harrylin-hyl @zxt881108 @lunachy For all who is interested in LSTR's FPS.  #19 

I've re-implemented LSTR and tested its performance on a single 2080 Ti (standard edition, no OC, also my hard disk is not SSD) [here](https://github.com/voldemortX/pytorch-auto-drive/blob/master/docs/BENCHMARK.md).

I've confirmed that, as @liuruijin17 observed, `batch_size=1` in the standard 360x640 resolution is not enough to reach the full performance of a large GPU (360x640 & 1080x1920 yields similar speed). So I go with common practice for testing real-time models and changed the input resolution. The results are (it is indeed very fast, essentially achieves real-time in 2K, without special optimizations for transformers):

| method | backbone | resolution | FPS | FLOPS(G) |
| :---: | :---: | :---: | :---: | :---: |
| LSTR | ResNet18s | 360 x 640 | 92.45 | 1.15 |
| LSTR | ResNet18s | 1080 x 1920 | 91.23 | 10.20 |
| LSTR | ResNet18s | 2160 x 4320 | 23.60 | 40.75 |

The only architecture diff in my current re-implementation to the original is I use 2-class cross-entropy (which saves 33 parameters) and no frozen the 1st BN (which adds 32 parameters). thop counts the parameters as 0.74M, if you count as the original code did, you will get 765786.
