### ISSUE TITLE
cannot load LSTR_500000.pkl

### ISSUE THREAD

**Issue by graphnj** [liuruijin17/LSTR#26]
File "/home/xx/ailab/LSTR/db/tusimple.py", line 114, in __init__
    self._load_data()
  File "/home/xx/ailab/LSTR/db/tusimple.py", line 137, in _load_data
    self.max_points) = pickle.load(f)
TypeError: 'int' object is not iterable

>>> f=open('./cache/nnet/LSTR/LSTR_500000.pkl','rb')
>>> pickle.load(f)
119547037146038801333356

**Comment by liuruijin17** [comment]
Sorry for being late, tough months about lots of deadlines.

It seems the bug happens when loading the generated .pkl dataset file, not the pre-trained model. Since others do not encounter your issue so, more details can help a lot.

**Comment by bclchenliang** [comment]
> File "/home/xx/ailab/LSTR/db/tusimple.py", line 114, in **init**
> self._load_data()
> File "/home/xx/ailab/LSTR/db/tusimple.py", line 137, in _load_data
> self.max_points) = pickle.load(f)
> TypeError: 'int' object is not iterable
> 
> > > > f=open('./cache/nnet/LSTR/LSTR_500000.pkl','rb')
> > > > pickle.load(f)
> > > > 119547037146038801333356

Have you solved this problem?  thank you.

**Comment by liuruijin17** [comment]
The torch model file can not directly load by pickle, it can be loaded by `torch.load()`

**Comment by dengbin1010** [comment]
> File "/home/xx/ailab/LSTR/db/tusimple.py", line 114, in **init**
> self._load_data()
> File "/home/xx/ailab/LSTR/db/tusimple.py", line 137, in _load_data
> self.max_points) = pickle.load(f)
> TypeError: 'int' object is not iterable
> 
> > > > f=open('./cache/nnet/LSTR/LSTR_500000.pkl','rb')
> > > > pickle.load(f)
> > > > 119547037146038801333356

Have you solved this problem? thank you.
