### ISSUE TITLE
关于模型预测的参数的疑问

### ISSUE THREAD

**Issue by nicheng0019** [liuruijin17/LSTR#28]
你好，请教一个问题：
根据论文中的式子[（3）、（4）](https://arxiv.org/pdf/2011.04233.pdf)，
模型预测的参数中的b'' 、 f''、 b'''满足b'' * f'' = b'''，如果模型预测出来的值不满足这个式子是怎么处理的？看代码里好像没有处理。
谢谢！

**Comment by liuruijin17** [comment]
您好，
按照(3)的三角函数关系，确实存在上述等式约束。
我在实现时用(4)，不引入三角函数的值域和三角变化约束，增加输出自由度是为了减少约束。因为约束拉满并未带来实质涨点而去掉约束可以覆盖一些更松弛的问题。

如果想物理约束拉满的话就用(3)式定义输出，以（k',φ,f,m',n',b'）根据(3)计算u'，同时规定好φ的值域。但体感出现了几次不收敛（训练一会损失上升了:joy:），可能是我没做预训练（预训练可以再涨点）或者有比较危险的“输出乘输出除以输出”的计算操作，所以为了减少tricks并稳定起见用得(4)。

**Comment by nicheng0019** [comment]
好的，非常感谢
