### ISSUE TITLE
API for testing other data?

### ISSUE THREAD

**Issue by OpenBanboo** [liuruijin17/LSTR#30]
This is great work! Quite light model with quite fast speed! Just wandering if you provided any API for testing any image others collected?

**Comment by liuruijin17** [comment]
Sorry for being late, tough months about lots of deadlines.
Thanks for your interest!
It's very very great to develop an API for the community, but it might not my top priority.
Images collected by others can be directly tested by provided pre-trained models using the current protocol (see the README.md), which is not well written..., so sorry for the inconvenience caused to you.

**Comment by OpenBanboo** [comment]
Thanks for the response! 

I used the following command provided in the README file to test some images I collected offline:
`python test.py LSTR --testiter 500000 --modality images --image_root ./ --debug`

Just wandering why would we need to assign iterations when testing? `(--testiter 500000)`

Looks like the pre-trained model fits the TuSimple samples pretty well:
![1](https://user-images.githubusercontent.com/14226287/105877334-b9269e80-5fb4-11eb-8cd7-e6e7e4c80284.jpg)

However, it does not shows very good result on my samples collected offline:
![frame5](https://user-images.githubusercontent.com/14226287/105877498-ebd09700-5fb4-11eb-906d-9f58effe71cf.jpg)
![frame2](https://user-images.githubusercontent.com/14226287/105877574-00149400-5fb5-11eb-8f4b-c09a6d81a147.jpg)

Any thoughts about these results? Is it because of the pre-trained model overfitting on the original TuSimple dataset? Or because of the camera angle/view's difference. Why the draw lanes so long considering the lanes are only located at the bottom of my images?

**Comment by hossam-sudo** [comment]
how did you test on your own images? where did you put your test images?

**Comment by OpenBanboo** [comment]
According to the README, you can evaluate with your own image by storing your images in ./images, then the detected results will be saved in ./detections:

`python test.py LSTR --testiter 500000 --modality images --image_root ./ --debug`

**Comment by OpenBanboo** [comment]
I modified my front camera's position and angle to make it more like the TuSimple training image. The results looks much better now:
![frame0](https://user-images.githubusercontent.com/14226287/106707297-d5729e80-65a5-11eb-93b6-83fd0f143b9e.jpg)
![frame92](https://user-images.githubusercontent.com/14226287/106707318-dc011600-65a5-11eb-82a9-8261948435fb.jpg)
![frame359](https://user-images.githubusercontent.com/14226287/106707333-e02d3380-65a5-11eb-9dc0-d74e30a31dc6.jpg)
