### ISSUE TITLE
No cache file found.

### ISSUE THREAD

**Issue by Gooddz1** [liuruijin17/LSTR#32]
loading from cache file: ./cache\tusimple_['label_data_0313', 'label_data_0601', 'label_data_0531'].pkl
No cache file found...

FileNotFoundError: [Errno 2] No such file or directory: '../../TuSimple\\LaneDetection\\label_data_0313.json'
  why?

**Comment by haige-algo** [comment]
I meet the same error, I think this error caused by test image dataset path

**Comment by hossam-sudo** [comment]
did anyone solve this issue?

**Comment by animesh-007** [comment]
> did anyone solve this issue?

Yes. I was facing the same issue. The issue which caused this error to me was due to not following the given folder structure properly.

**Comment by Gooddz1** [comment]
> 我遇到相同的错误，我认为此错误是由测试图像数据集路径引起的


> I meet the same error, I think this error caused by test image dataset path

Have you solved the problem

**Comment by Gooddz1** [comment]
> did anyone solve this issue?

Have you solved the problem

**Comment by Gooddz1** [comment]
> > did anyone solve this issue?
> 
> Yes. I was facing the same issue. The issue which caused this error to me was due to not following the given folder structure properly.

Have you solved the problem

**Comment by Gooddz1** [comment]
> > 有人解决了这个问题吗？
> 
> 是的。我面临着同样的问题。对我造成此错误的问题是由于未正确遵循给定的文件夹结构。


TuSimple/
    LaneDetection/
        clips/
        label_data_0313.json
        label_data_0531.json
        label_data_0601.json
        test_label.json
    LSTR/
I follow this folder format, but still have this problem

**Comment by Gooddz1** [comment]
> > did anyone solve this issue?
> 
> Yes. I was facing the same issue. The issue which caused this error to me was due to not following the given folder structure properly.

Do you need to join this file(tusimple_label_data_0313.pkl、tusimple_label_data_0601.pkl、tusimple_label_data_0531.pkl)？

**Comment by Gooddz1** [comment]
> did anyone solve this issue?

Have you solved the problem

**Comment by Gooddz1** [comment]
> I meet the same error, I think this error caused by test image dataset path

Have you solved the problem

**Comment by animesh-007** [comment]
> > > did anyone solve this issue?
> > 
> > 
> > Yes. I was facing the same issue. The issue which caused this error to me was due to not following the given folder structure properly.
> 
> Do you need to join this file(tusimple_label_data_0313.pkl、tusimple_label_data_0601.pkl、tusimple_label_data_0531.pkl)？

No. I just downloaded the whole dataset and kept it in the same format as the readme suggest.

**Comment by zsffuture** [comment]
Is the path problem, trace source debug look will know, modify into their own file path
