### ISSUE TITLE
About the backbone

### ISSUE THREAD

**Issue by voldemortX** [liuruijin17/LSTR#41]
@liuruijin17 Hi! I'm re-implementing your great method.
I'm just checking the modifications you made on the ResNet-18 backbone. Except for the width change, I find there seems to be also [a drop of basicblock](https://github.com/liuruijin17/LSTR/blob/6044f7b2c5892dba7201c273ee632b4962350223/config/LSTR.json#L30) at `layer1`, other settings (not counting frozen BN and width change) are exactly the same as He's ResNet-18, could you check if I'm correct?

**Comment by liuruijin17** [comment]
Yes, you are correct. The first block only has one 'BasicBlock' layer.

**Comment by voldemortX** [comment]
Thanks! Closing issue.
