### ISSUE TITLE
请问项目中已经训练好的模型是否支持转换成onnx

### ISSUE THREAD

**Issue by wycrystal** [liuruijin17/LSTR#42]
请问项目中已经训练好的模型是否支持转换成onnx？如果支持的话，能否给一些指导，谢谢！

**Comment by liuruijin17** [comment]
您好,
模型应该是支持转换的,只不过我没有ONNX以及模型转换方面的专业知识,所以抱歉没法帮助您!

**Comment by lucky-xu-1994** [comment]
> 请问项目中已经训练好的模型是否支持转换成onnx？如果支持的话，能否给一些指导，谢谢！

have you converted the model to ONNX succsessfully? if yes, how? Thanks!
