### ISSUE TITLE
ONNX( 'NetworkFactory' object has no attribute 'training')

### ISSUE THREAD

**Issue by lucky-xu-1994** [liuruijin17/LSTR#47]
when I try to convert this model to ONNX ,I have made mistakes.
1. I added some code in test.py to convert onnx.
![image](https://user-images.githubusercontent.com/57120921/116516247-f70ec800-a8ff-11eb-8317-c221f4598eb0.png)

2. the error like this:
![image](https://user-images.githubusercontent.com/57120921/116516665-71d7e300-a900-11eb-8770-9db784ecea37.png)

I would be grateful if there is anyone could give me some advise! thanks.

**Comment by lucky-xu-1994** [comment]
ok, I have solved it . the key is to choose the model for building network to export!

**Comment by ldol31627** [comment]
> ok, I have solved it . the key is to choose the model for building network to export!

How did you solve it ?

**Comment by ldol31627** [comment]
I have solved it .
change: torch.onnx._export(nnet ...)
to: torch.onnx._export(nnet.model ...)

**Comment by lhxy1991** [comment]
@lucky-xu-1994 @ldol31627 how did you solve it?  net -> net.model? and why inputs need ['images','mask'] ?
