### ISSUE TITLE
 lane model parameters (k,m,n,b)

### ISSUE THREAD

**Issue by flj151** [liuruijin17/LSTR#5]
hello,I want to know what are the physical meanings of the lane model parameters (k,m,n,b),Thank you!

**Comment by liuruijin17** [comment]
Hi,
(k, m, n, b) are coefficients of a cubic curve that approximates a lane on the road from the 'bird's eye view.'
(k, m, n) describe how the lane bends (left or right, small or large curvature), and b represents the positional offset.

**Comment by flj151** [comment]
Thank you for your reply！
Are they the same as the road coefficients (C0,C1,C2,C3) produced by the camera sensor (e.g. Moblieye Q3)?

**Comment by liuruijin17** [comment]
Sorry, I am not familiar with the sensor you are referring to.
