### ISSUE TITLE
About Formula （1）

### ISSUE THREAD

**Issue by flj151** [liuruijin17/LSTR#53]
Is the formula vehicle coordinate system or geodetic coordinate system?How do I convert Formula 4 to Formula 1?

**Comment by liuruijin17** [comment]
Eq (1) is on vehicle coordinate which only considers two world axes (horizontal and depth)

Eq (4) is the only representation for lanes on the images. We do not intend to transfer it to Eq (4).

Eq (3) can be used to transfer from image to vehicle coordinate if you formulate lanes on images according to your sensor's parameters.
