### ISSUE TITLE
你好，在无车道线的环境下检测出车道线该如何解决呢？

### ISSUE THREAD

**Issue by Chenfy13** [liuruijin17/LSTR#54]

**Comment by Chenfy13** [comment]
没车道线的图片应该怎么标注呢？

**Comment by liuruijin17** [comment]
Hi,
无线图中检测出车道线一般是由于
1无线图中有标注
2无线图无标注但与有线图较相似
3检出线score不高，阈值滤掉（比较没用）

对应的标注处理方法有三个
1无线图中‘猜测’大体的车道线进行标注（CULane数据集的做法）
2去掉无线图

在视频测试中，若无线图仅出现几帧，可利用滤波，跟踪等时序平滑去除
