### ISSUE TITLE
how to set N when testing

### ISSUE THREAD

**Issue by tomorrow00** [liuruijin17/LSTR#55]
Hi, great work! I'd like to ask that how to set the lanes number N when testing. N is fixed during training, will the testing process output the same N with training?

**Comment by liuruijin17** [comment]
Hi, thanks a lot!

Yes, LSTR outputs N ‘lanes’ during testing. Those 'lanes' whose categories are 1 (0: background, 1: lane) would be the final lane predictions.

**Comment by tomorrow00** [comment]
> Hi, thanks a lot!
> 
> Yes, LSTR outputs N ‘lanes’ during testing. Those 'lanes' whose categories are 1 (0: background, 1: lane) would be the final lane predictions.

Appreciate that, it helps me so much!
