### ISSUE TITLE
How to label and train my own dataset?

### ISSUE THREAD

**Issue by lvxuanxuan123** [liuruijin17/LSTR#59]
1. What format should the labeled dataset be? Is a picture corresponding to a json file? 
2. How to modify the code?  such as the LSTR.json file?

**Comment by liuruijin17** [comment]
Hi, thanks for your interest!
1. Please refer to #49 
2. I will make a customized tutorial in a few days.

**Comment by lvxuanxuan123** [comment]
Hi, thanks for your answer and I will look forward your updates!

**Comment by Timooooooooooo** [comment]
I will look forward your updates!
