### ISSUE TITLE
Question about equation (10)?

### ISSUE THREAD

**Issue by yulongshan** [liuruijin17/LSTR#6]
Thanks for your great work!  
I have a question about equation 10, and I think it should be X = Z*u/fu according to the perspective projection. What's more you ignores the cu and cv parameters of  camera instrinc.

**Comment by liuruijin17** [comment]
Hi, fu is the width (in meter) of a pixel / focal length (in meter), so u * fu is in meter / meter. Then Z is in meter, and X = (meter / meter) * meter so in meter.

Yes, we ignore translation offsets for simplicity.

**Comment by yulongshan** [comment]
Thanks for your relying, And I usually consider the camera instrinc matrix as  [fx,0 ,cx,0,fy,cy,0,0,1] . So I calculate like this 
![F6AD057E3E7224F874A4EA2CF5D4313C](https://user-images.githubusercontent.com/34642931/99866483-76c79680-2bec-11eb-9426-f8c8392a0ce5.png)
**But does fu = 1/fx ,fv = 1/ fy in your paper?**

**Comment by liuruijin17** [comment]
Perhaps the physical quantities and physical meaning of the camera parameters are not understood in the same way. Here's how we consider it.
![eq10](https://user-images.githubusercontent.com/29913368/99867349-e9884000-2bf3-11eb-9c9d-be6472a2d1d4.jpg)
![eq102](https://user-images.githubusercontent.com/29913368/99867496-f8bbbd80-2bf4-11eb-95f8-45d222f6f480.jpg)

**Comment by yulongshan** [comment]
Thans very much!

**Comment by yulongshan** [comment]
您好，很抱歉再次打扰您，我又一次研究您的论文时，不太理解公式12,
[cid:d53836e5-f8d5-427b-876e-e48d5e25a852]
为什么可以将旋转矩阵作用在像素坐标上，还有您的f和fu，fv是什么关系呢？
一般旋转矩阵R不应该K（RX）/Z = [uv]这样作用吗？其中K为相机内参，X为三维点。
f不应该是相机固有参数为什么会在发生pithc角时变化，您是将u,v,f当作三维点去做变化吗？

Sent from Outlook<http://aka.ms/weboutlook>

________________________________
