### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by Timooooooooooo** [liuruijin17/LSTR#64]
Hi，按照要求的Tusimple格式放置好，一直报这个错AttributeError: 'NoneType' object has no attribute 'shape'。LSTR文件夹里放的是整个项目文件吗。

**Comment by Timooooooooooo** [comment]
root@1ebbc1f27b57:/data/TuSimple/LSTR# python train.py LSTR
loading all datasets TUSIMPLE...
using 4 threads
loading from cache file: ./cache/tusimple_['label_data_0313', 'label_data_0601', 'label_data_0531'].pkl
loading from cache file: ./cache/tusimple_['label_data_0313', 'label_data_0601', 'label_data_0531'].pkl
loading from cache file: ./cache/tusimple_['label_data_0313', 'label_data_0601', 'label_data_0531'].pkl
loading from cache file: ./cache/tusimple_['label_data_0313', 'label_data_0601', 'label_data_0531'].pkl
loading from cache file: ./cache/tusimple_['label_data_0531'].pkl
len of training db: 7710
len of testing db: 2826
freeze the pretrained network: False
start prefetching data...
shuffling indices...
start prefetching data...
shuffling indices...
Traceback (most recent call last):
Traceback (most recent call last):
  File "train.py", line 50, in prefetch_data
    data, ind = sample_data(db, ind)
  File "train.py", line 50, in prefetch_data
    data, ind = sample_data(db, ind)
  File "/data/TuSimple/LSTR/sample/tusimple.py", line 80, in sample_data
    return globals()[system_configs.sampling_function](db, k_ind)
  File "/data/TuSimple/LSTR/sample/tusimple.py", line 38, in kp_detection
    mask  = np.ones((1, img.shape[0], img.shape[1], 1), dtype=np.bool)
  File "/data/TuSimple/LSTR/sample/tusimple.py", line 80, in sample_data
    return globals()[system_configs.sampling_function](db, k_ind)
  File "/data/TuSimple/LSTR/sample/tusimple.py", line 38, in kp_detection
    mask  = np.ones((1, img.shape[0], img.shape[1], 1), dtype=np.bool)
AttributeError: 'NoneType' object has no attribute 'shape'
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by liuruijin17** [comment]
Hi, 
It happens when the "img" is not "cv2.imread(image_path)" correctly, you should check the "image_path" first.

**Comment by Timooooooooooo** [comment]
> 
Thankyou

**Comment by lvxuanxuan123** [comment]
> > 
> 
> Thankyou

hello! I met this error today, and did you solved this problem?

**Comment by Timooooooooooo** [comment]
> 

check your img_path, and check wheter the "cv.imread" has correct things, you can print them.
