### ISSUE TITLE
train error happens when I train my own data use the custom branch

### ISSUE THREAD

**Issue by lvxuanxuan123** [liuruijin17/LSTR#67]
Traceback (most recent call last):
  File "/home/anaconda3/envs/lstr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/anaconda3/envs/lstr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "train.py", line 54, in prefetch_data
    raise e
  File "train.py", line 50, in prefetch_data
    data, ind = sample_data(db, ind)
  File "/home/LSTR/LSTR-custom/sample/custom.py", line 71, in sample_data
    return globals()[system_configs.sampling_function](db, k_ind)
  File "/home/LSTR/LSTR-custom/sample/custom.py", line 31, in kp_detection
    mask  = np.ones((1, img.shape[0], img.shape[1], 1), dtype=np.bool)
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by liuruijin17** [comment]
Hi,
It happens when the image is not loaded correctly. Please check out the path you pass to cv2.imread at
https://github.com/liuruijin17/LSTR/blob/7e4e4f1ad5844be492007cf89e81e574c764d307/sample/custom.py#L30

**Comment by lvxuanxuan123** [comment]
> Hi, It happens when the image is not loaded correctly. Please check out the path you pass to cv2.imread at
> 
> https://github.com/liuruijin17/LSTR/blob/7e4e4f1ad5844be492007cf89e81e574c764d307/sample/custom.py#L30

hello, I know the problem is in this line, but the print path shows that it seems to be fine. My dataset is stored in raws. And the error still exists.
![屏幕截图](https://user-images.githubusercontent.com/32082480/145671187-347e6a23-43f9-4b6b-a2a3-831e01eb94a7.png)

**Comment by lvxuanxuan123** [comment]
@liuruijin17 Dear author, I solved this problem by converting the image format from .png to .jpg.

**Comment by AvneeshKhanna** [comment]
Hi
I have the same issue. My files are in jpg only. But I am still getting the error

**Comment by lvxuanxuan123** [comment]
> Hi I have the same issue. My files are in jpg only. But I am still getting the error

You can print the path as what I did.

**Comment by AvneeshKhanna** [comment]
I see the following piece of code which might be setting the image path in `db/custom.py` line 129:

`image_name = anno_name[:-4] + '.jpg'`

Why are we setting it using [:-4]? Is this what might be causing the error? Because I printed the path, my files are named 0045.jpg, but the code is picking only 5.jpg as file name. I am uploading my files from a Windows machine to Ubuntu AWS instance, if it helps.
