### ISSUE TITLE
Trouble training on custom dataset

### ISSUE THREAD

**Issue by kaustabpal** [liuruijin17/LSTR#71]
I have followed the instructions in the ```train_test_custom_data.md``` file and created a dataset of 24 images. While training the images in the results directory are showing the wrong groundtruths. 
![iter_100_layer_0_gt](https://user-images.githubusercontent.com/15041798/147474731-46cc17a8-f54a-4578-94ed-e066cd85f2ac.jpg)
Each row of the ```.txt``` file contains the x1, y1, x2, y2, ... of each lane and x1 is the x pixel coordinate of the lane point and y1 is the y pixel coordinate of the lane point. Kindly help us out if we are doing something wrong.

**Comment by kaustabpal** [comment]
Solved it. The code was using the .pkl file of the previous dataset which contained the annotations of the previous dataset. Deleting that pkl file solved the issue. Thanks anyways

**Comment by AvneeshKhanna** [comment]
Hi
Could you tell me how did you test on your custom dataset? I cloned the custom branched and used their tutorial. Seemed like the code is not reading my test images.

**Comment by Galaxy-Ding** [comment]
> ious dataset which contained the annotations of the pre
hi
Can you tell me how to fix it? what i have done : I re-labeled the data and deleted all the files in the cache folder and commented out the code to load the pkl, but it still comes up with the same wrong label as your picture
