### ISSUE TITLE
Curvature values

### ISSUE THREAD

**Issue by k-nayak** [liuruijin17/LSTR#87]
hello, I would like to know if the model can accurately detect lanes and also give the curvature of the lane in real-time? As I am looking for a DNN based curvature detection instead of a traditional vision algorithm. Any feedback will be very helpful. Thanks in advance.

**Comment by liuruijin17** [comment]
Sorry for the very late response!

Yes, you can calculate curvatures based on 
![屏幕截图 2022-05-17 113308](https://user-images.githubusercontent.com/29913368/168723295-3e508701-58ea-4a6b-a2ea-3aab23f67809.png)

[https://en.wikipedia.org/wiki/Curvature](url)
