### ISSUE TITLE
How to install cpools==0.0.0

### ISSUE THREAD

**Issue by Kaimingfan** [liuruijin17/LSTR#9]

**Comment by lunachy** [comment]
ignore it!
docker pull pytorch/pytorch:1.6.0-cuda10.1-cudnn7-runtime
pip install -i https://pypi.tuna.tsinghua.edu.cn/simple thop scikit-learn ujson scipy tabulate imgaug opencv-python h5py
apt install libgl1-mesa-glx libglib2.0-0
